[data]
data_path = '/scratch/SDF25/DeepCube_UC4a/S1/Train/' # enter your path for the S1 train set
mean = [0.5118, 0.5118, 0.5118] #S1 mean greyscale
std = [0.2717, 0.2717, 0.2717] #S1 std greyscale

[crops]
global_crops_scale = [0.4, 1.0]
local_crops_scale = [0.05, 0.4]
local_crops_number = 8

[model]
model = 'vit_tiny' # embed_dim=192, depth=12, num_heads=3
patch_size = 16
out_dim = 16384 # complex and large datasets values like 65k work well
use_bn_head = false # use batch norm in head
norm_last_layer = true #  normalize the last layer of the DINO head, typically set this paramater to False with vit_small and True with vit_base

[DINO]
warmup_teacher_temp = 0.02 # Initial value for the teacher temperature, Try decreasing it if the training loss does not decrease
teacher_temp = 0.04
warmup_teacher_temp_epochs = 30 # 30 is default?
momentum_teacher = 0.996 # Base EMA parameter for teacher update. The value is increased to 1 during training with cosine schedule. We recommend setting a higher value with small batches: for example use 0.9995 with batch size of 256.""")

[train]
device = 'cpu'
epochs = 100
lr = 5e-2
min_lr=5e-4
warmup_epochs = 10
weight_decay = 0.04
weight_decay_end = 0.4
batch_size = 128
num_workers = 8
pin_memory = false
use_fp16 = false
clip_grad = 3.0
freeze_last_layer = 1
