[data]
train_path = '/scratch/SDF25/DeepCube_UC4a/S1/Train/' # enter your path for the S1 train set
val_path = '/scratch/SDF25/DeepCube_UC4a/S1/Test/'
c1_val = true
c1_val_path = '/scratch/SDF25/DeepCube_UC4a/C1/'
mean = [0.5118, 0.5118, 0.5118] #S1 mean greyscale
std = [0.2717, 0.2717, 0.2717] #S1 std greyscale

[crops]
global_crops_scale = [0.4, 1.0]
local_crops_scale = [0.05, 0.4]
local_crops_number = 8

[model]
model = 'resnet50' # embed_dim=384, depth=12, num_heads=8
patch_size = 16
out_dim = 16384 # complex and large datasets values like 65k work well
use_bn_head = false # use batch norm in head
norm_last_layer = true #  normalize the last layer of the DINO head, typically set this paramater to False with vit_small and True with vit_base
checkpoint_path = 'model_checkpoints/ResNet50_o16384_wtt01_tt03_mt9995_no_oversampling.pth'

[DINO]
warmup_teacher_temp = 0.02 # Initial value for the teacher temperature, Try decreasing it if the training loss does not decrease
teacher_temp = 0.04
warmup_teacher_temp_epochs = 30 # 30 is default?
momentum_teacher = 0.996 # Base EMA parameter for teacher update. The value is increased to 1 during training with cosine schedule. We recommend setting a higher value with small batches: for example use 0.9995 with batch size of 256.""")
oversampling = false

[linear]
n_last_blocks = 4
avgpool_patchtokens = false
num_labels = 2
lr = 1e-5 #ViT0.0005 

[train]
device = 'cuda'
optim = 'sgd' #adamw for ViT, sgd for ResNet50
epochs = 101 #500 for DINO, 100 for linear
lr = 0.04 #1e-3 ViT, 0.03 ResNet50
min_lr=6e-5 #1e-4 Vit, 7e-6 ResNet50
warmup_epochs = 20
weight_decay = 1e-4 #0.04 ViT, 1e-4 ResNet50
weight_decay_end = 1e-4 #0.4 ViT, 1e-4 ResNet50
batch_size = 256 #256 for ViTS16 and linear training runs, 64 for ViTS8 training run
train_eval_batch_size = 1 #training set batch size for knn eval (maximise sample count)
val_batch_size = 32 #val batch size for knn eval and linear eval
c1_val_batch_size = 1
num_workers = 32
pin_memory = true
use_fp16 = true
clip_grad = 3.0
freeze_last_layer = 1
