[data]
input_size = 224
# mean = [0.5118, 0.5118, 0.5118] #S1 mean greyscale
# std = [0.2717, 0.2717, 0.2717] #S1 std greyscale
mean = [0.4156, 0.4156, 0.4156] # Synthetic InSAR
std = [0.4223, 0.4223, 0.4223] # Synthetic InSAR
# train_path = '/scratch/SDF25/DeepCube_UC4a/S1/Train/' # enter your path for the S1 train set
train_path = '/scratch/SDF25/PrototypeInSAR/synth/' # U:\scratch\SDF25\PrototypeInSAR\synth
# val_path = '/scratch/SDF25/DeepCube_UC4a/S1/Test/'
val_path = '/scratch/SDF25/PrototypeInSAR/validation_synthetic'
c1_path = '/scratch/SDF25/DeepCube_UC4a/C1/'
num_classes = 2
# output_dir = '/home/conradb/git/ifg-ssl/S1_C1/outputs/'

[model]
model = 'vit_base_patch16'
global_pool = false
# checkpoint_path = 'model_checkpoints/MAE_VitB16_224_no_oversampling.pth'
checkpoint_path = 'model_checkpoints/SynInSAR_MAE_VitB16_224_no_oversampling.pth'

[train]
device = 'cuda'
batch_size = 256 # consider changing to 256
val_batch_size = 20
c1_batch_size = 1
blr = 1e-2 # consider changing to 1.5e-4
min_lr = 0
weight_decay = 0.0001
epochs = 101
warmup_epochs = 10
num_workers = 32
pin_memory = true
